### ISSUE TITLE
Errors in NotebookUI plot

### ISSUE THREAD

**Issue by goodboychan** [jckantor/TCLab#100]
Hi,
Currently, I tried to use tclab in jupyter notebook.
(TCLab v0.4.6, firmware 1.01)
I followed instruction on this repo. But when I plot the figure, there are no result for T, Q etc.
Besides, error log is printed like this

``` warning
ERROR:tornado.application:Exception in callback <bound method NotebookUI.update
of <tclab.gui.NotebookUI object at 0x000000000996C668>>
Traceback (most recent call last):
  File "V:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 1026, in _run
    return self.callback()
  File "V:\Anaconda3\lib\site-packages\tclab\gui.py", line 177, in update
    self.plotter.update(labtime.time())
  File "V:\Anaconda3\lib\site-packages\tclab\historian.py", line 283, in update
    self.historian.update(tnow)
  File "V:\Anaconda3\lib\site-packages\tclab\historian.py", line 148, in update
    v = valuefunction()
  File "V:\Anaconda3\lib\site-packages\tclab\tclab.py", line 191, in scan
    T2 = self.T2  # float(self.receive())
  File "V:\Anaconda3\lib\site-packages\tclab\tclab.py", line 173, in Q1
    msg = 'Q1' + sep + str(clip(val))
  File "V:\Anaconda3\lib\site-packages\tclab\tclab.py", line 127, in send_and_re
ceive
    print(type(self.receive()))
ValueError: could not convert string to float:
```

How can I handle this?

Thanks in advance.

**Comment by alchemyst** [comment]
It appears as though your hardware is sending a value which we do not recognize. Could you please execute the following and paste the result?

```
import tclab
tclab.diagnose()
```

**Comment by goodboychan** [comment]
Sorry for late response.
Here is my output from dianose:
----------------------
>>> import tclab
>>> tclab.diagnose()
Looking for Arduino on  ...
Arduino Leonardo found on port COM10

Testing TCLab object in debug mode
----------------------------------
TCLab version 0.4.6
Sent: "Q1 0"
Return: "0.00"
Sent: "VER"
Return: "TCLab Firmware Version 1.01"
Arduino Leonardo connected on port COM10 at 115200 baud.
TCLab Firmware Version 1.01.
Sent: "Q2 0"
Return: "0.00"
Reading temperature
Sent: "T1"
Return: "22.12"
22.12
Sent: "Q1 0"
Return: "0.00"
Sent: "Q2 0"
Return: "0.00"
Sent: "X"
Return: "Stop"
TCLab disconnected successfully.

Testing TCLab functions
-----------------------
TCLab version 0.4.6
Arduino Leonardo connected on port COM10 at 115200 baud.
TCLab Firmware Version 1.01.
Testing LED. Should turn on for 10 seconds.
Countdown: 0

Reading temperatures
T1 = 22.16 °C, T2 = 21.67 °C

We will now turn on the heaters, wait 30 seconds and see if the temperatures hav
e gone up.
Countdown: 0

T1 started a 22.16 °C and went to 29.12 °C
T2 started a 21.67 °C and went to 26.41 °C

TCLab disconnected successfully.

Diagnostics complete
------------

Thanks.

**Comment by alchemyst** [comment]
OK, it looks like your unit is working correctly and the Python code is working as well. Please paste the code in your notebook which was causing the problem.

**Comment by goodboychan** [comment]
Nothing Special. I just ran the example notebook.
Here is my code snippets:

```
from tclab.gui import NotebookUI
%matplotlib notebook
interface = NotebookUI()

interface.gui
```
I intend to show the real sensor data on jupyter dynamically.
Thanks.

**Comment by alchemyst** [comment]
Can you please describe in more detail what happens when you run the code?

1. Do you see the following UI when running the cells?

![image](https://user-images.githubusercontent.com/236588/40408065-a50d4c98-5e66-11e8-83dc-52a896335e01.png)

2. Does the interface work when you check the "Use model" box, click "Connect" and then "Start"? You should see something like this:
![image](https://user-images.githubusercontent.com/236588/40408519-2aa2a208-5e68-11e8-9f0a-c92dc3542d9f.png)

3. If you re-run the the notebook and just click "Connect", but not "Start", do you see the message about connecting to the TClab and a set of axes appear?

4. Now, if you got to this point and you click "Start", describe in detail what happens (does the error you pasted occur immediately, or only after a while?

**Comment by alchemyst** [comment]
It looks like the unit is sending a blank line (`ValueError: could not convert string to float:`). Could you please try to update your firmware? You've got quite an old version there.

 https://github.com/jckantor/TCLab-sketch

**Comment by goodboychan** [comment]
You`re right. Currently, we are using v1.01
After firmware update, the problem is gone.
Thanks for your help!
