### ISSUE TITLE
Bump version and push to PyPI

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#103]
I think it's time for verson 0.4.7

**Comment by jckantor** [comment]
Sounds good.  I was just getting ready for a bump.  I want to take care of
the clock sync issue.

I've also done updates on the firmware.  There was a missing line in the
1.4.0 that needed to be fixed, and I took out a few lines that would only
apply to very obsolete versions of the Arduino IDE.

I'm considering stripping out the webusb driver as well. It's necessary for
use with Vocareum, but then Google removed webusb from Chrome for a while.
It's now back in Chrome, so there's a potential use case. And there also be
someone out there who would want to use TCLab with a hosted version of the
notebooks via Binder or Google Colab.  So I'm on the fence.

Jeff

**Comment by alchemyst** [comment]
I think it’s always easier to maintain smaller packages, so I’m very much in the “when in doubt, take it out” mind.

Thanks for pushing out the new version.

**Comment by jckantor** [comment]
I've removed webusb from the Arduino firmware, and designated this version
1.5.0. It will eliminate the annoying connect message generated by Chrome.

Jeff
