### ISSUE TITLE
Cannot convert string to float

### ISSUE THREAD

**Issue by ethangunl** [jckantor/TCLab#104]
On both windows 10 operating systems on my laptop and desktop, using [tclab F](https://apmonitor.com/do/index.php/Main/TCLabF), I ran into this issue which prevented connecting to the arduino. We tried multiple arduinos, then downgraded from 0.4.8 to 0.4.6, and the lab worked.

```
TCLab version 0.4.8
Traceback (most recent call last):
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 63, in __init__
    self.connect(baud=115200)
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 114, in connect
    self.Q1(0)  # fails if not connected
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 192, in Q1
    return self.send_and_receive(msg, float)
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 146, in send_and_receive
    return convert(self.receive())
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 69, in __init__
    self.connect(baud=9600)
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 108, in connect
    raise AlreadyConnectedError('You already have an open connection')
tclab.tclab.AlreadyConnectedError: You already have an open connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Ethan/PycharmProjects/DynOpt/venv/Lab F (in class).py", line 14, in <module>
    a = TCLab()
  File "C:\Users\Ethan\Anaconda3\lib\site-packages\tclab\tclab.py", line 75, in __init__
    raise RuntimeError('Failed to Connect.')
RuntimeError: Failed to Connect.

Process finished with exit code 1
```

**Comment by ethangunl** [comment]
I worked on this together with @dhill2522

**Comment by jckantor** [comment]
Thanks for sending this.  Do you know the which version of the sketch
(i.e., Arduino firmware) you are working with?

Thanks,
Jeff

**Comment by ethangunl** [comment]
I can look in an hour or so, but we tried multiple arduinos that Daniel
had. I uploaded the version with the arduino from the class website a day
ago to make sure I had the updated firmware.

- Ethan

**Comment by jckantor** [comment]
Thank you.

I've not been able to reproduce the bug.  We did experience a similar
problem a few months ago, and was resolved when we did some updates to the
firmware side of things.

The lastest version of the Arduino firmware is 1.5.0 available here:
https://github.com/jckantor/tclab-sketch  Would you be able to try that out?

Thanks,
Jeff

**Comment by dhill2522** [comment]
Thanks for looking into this. 

It did not look like a sketch issue when we looked at it as it behaved the same with multiple fresh TCLab Arduinos. I will see if I can reproduce the bug on my system as soon as I get a chance.

Daniel

**Comment by ethangunl** [comment]
I used version 1.5 but I removed the first line of code to get rid of the
webusb not found error. It seems to work now with the upgraded tclab
version.

Thanks,

Ethan

**Comment by dhill2522** [comment]
I get the same result on Fedora 29 with TCLab Firmware version 1.01. It works fine with `tclab==0.4.6`, but fails with `tclab==0.4.8`. I will try with the updated sketch soon. 

Not a big problem, but good to know the latest tclab version is not necessarily backwards compatible with previous sketches.

**Comment by jckantor** [comment]
Yes, that's an issue we're facing. We tried to improve the whole connection
experience, but then this issue came up.

So I take it things are now working again with firmware 1.5.0?

Jeff

**Comment by dhill2522** [comment]
Yep, working great now.

Thanks!

**Comment by jckantor** [comment]
Excellent.

**Comment by Aluxide** [comment]
Using TCLab I experienced the same problem.
Suspecting the serial handling, a few lines have been added in the .ino file, and as a result the TCLab runs again.
Up until this point it performs stable. This might solve the problem for others.

Conditions:
	Operating system: 			Windows 10
	Python interpreter: 		Python 3.12.5 64bit
	Site packages (reinstalled): 	tclab 1.0.0
	Site packages (reinstalled):	pyserial 3.5
	Site packages (reinstalled):	serial 0.0.97
	C interpreter:				Arduino 2.3.2
	Board type: 				Teensy 4.0

Running .py file with the following lines,

```
import tclab
lab = tclab.TCLab(debug=True)
```

Running .ino file replicates the same error for,
- 	tclab_v1.ino version 1.4.3
- 	tclab_v2.ino version 2.0.1

Note: In order to use Teensy 4.0 the line (v2 line339) 'analogReference(EXTERNAL);' had to be uncommented.

The ValueError can be observed from the run & debug mode,

> Exception has occurred: ValueError
> could not convert string to float: ''
>   File "C:\Users\Kevin\Documents\Python\test.py", line 2, in <module>
>     lab = tclab.TCLab(debug=True)
>           ^^^^^^^^^^^^^^^^^^^^^^^
> ValueError: could not convert string to float: ''

Response observed at TERMINAL,

> TCLab version 1.0.0
> Sent: "Q1 0"
> Return: "0.000"
> Sent: "VER"
> Return: ""
> unknown device connected on port COM6 at 115200 baud.
> .
> Sent: "Q2 0"
> Return: ""

The return of nothing explains why tclab is unable to convert to float.

Adding the while loop after 'newData=true' to the function 'void readCommand()' (v2 at line133) empties the internal buffer of the serial,

```
void readCommand() {
  while (Serial && (Serial.available() > 0) && (newData == false)) {
    int byte = Serial.read();
    if ((byte != '\r') && (byte != nl) && (buffer_index < 64)) {
      Buffer[buffer_index] = byte;
      buffer_index++;
    }
    else {
      newData = true;
      while (Serial && (Serial.available() > 0)) {
        int superfluous = Serial.peek();
        if (superfluous == '\r' || superfluous == '\n') {
          (void)Serial.read();
        }
        else
          break;
      }
    }
  }   
}
```



Response observed at TERMINAL after added lines,

> TCLab version 1.0.0
> Sent: "Q1 0"
> Return: "0.000"
> Sent: "VER"
> Return: "TCLab Firmware 2.0.1 Unknown board"
> unknown device connected on port COM6 at 115200 baud.
> TCLab Firmware 2.0.1 Unknown board.
> Sent: "Q2 0"
> Return: "0.000"
