### ISSUE TITLE
Iterable import error when using python 3.10

### ISSUE THREAD

**Issue by juanmvenegas** [jckantor/TCLab#111]
When importing tclab into an environment with python 3.10, I get the following traceback error:

```python
import tclab
Traceback (most recent call last):

  File "C:\Users\juanmvenegasPC\AppData\Local\Temp\ipykernel_18148\1606910932.py", line 1, in <cell line: 1>
    import tclab

  File "C:\Users\juanmvenegasPC\anaconda3\envs\datasci\lib\site-packages\tclab\__init__.py", line 2, in <module>
    from .historian import Historian, Plotter

  File "C:\Users\juanmvenegasPC\anaconda3\envs\datasci\lib\site-packages\tclab\historian.py", line 6, in <module>
    from collections import Iterable

ImportError: cannot import name 'Iterable' from 'collections' (C:\Users\juanmvenegasPC\anaconda3\envs\datasci\lib\collections\__init__.py)
```

The issue is described [here](https://stackoverflow.com/a/72032097) and notes that since python 3.10 the iterables class has been removed from `collections` . As a solution it is suggested to use `collections.abc` instead. 

I got tclab to work by modifying `historian.py` to change the `Iterable` import:

```python
 from collections.abc import Iterable
```

**Comment by APMonitor** [comment]
To preserve compatibility with older versions, this is a proposed modification to `historian.py`:

```python
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```

**Comment by alchemyst** [comment]
I've fixed this in a different way, by reverting the type check where this is actually used to a try/catch. Thank you for reporting this.

**Comment by APMonitor** [comment]
@alchemyst - I get it now - you removed `from collections import Iterable` completely because it no longer exists in Python 3.10. Python packages typically retain backwards compatibility but it appears that this is an exception because of deprecation of that function. Will the `if isinstance(v, Iterable):` ever complete successfully because `Iterable` is no longer imported? Just trying to understand the proposed modifications.

Here is a discussion: https://stackoverflow.com/questions/1952464/in-python-how-do-i-determine-if-an-object-is-iterable that may help.

**Comment by alchemyst** [comment]
@APMonitor Have a look at [the commit](https://github.com/jckantor/TCLab/commit/a975c36d68ccbc3c0f6dade4ae99c0abc3271f81) that closed this issue. It does two things:

- Remove the faulty import
- Use try/catch logic instead of instance checking for the iterable check (this is the top answer to the question on StackOverflow you posted)

**Comment by APMonitor** [comment]
Several have contacted me about Python 3.10. Until a pypi.org (for pip install) update is made, please use this simple fix:

Go into historian.py in tclab module and change `from collections import Iterable` to `from collections.abc import Iterable`

Instructions are also added to the [help documentation for the tclab](https://apmonitor.com/pdc/index.php/Main/ArduinoSetup) - see FAQ.

**Comment by alchemyst** [comment]
Note that it is also possible to install straight from github using

```
pip install --upgrade https://github.com/jckantor/TCLab/archive/master.zip
```

**Comment by APMonitor** [comment]
Thanks for that suggestion. I've updated the FAQ to include this helpful tip. https://apmonitor.com/pdc/index.php/Main/ArduinoSetup

**Comment by kjkoster** [comment]
Can this be rolled into a release version, please? That would save many the bother of having to find this problem and fix it using non-release code.

**Comment by APMonitor** [comment]
We recently got the sad news that Jeff Kantor passed away. He was the maintainer of the `tclab` package so it looks like we'll need to continue to use:

```python
pip install --upgrade https://github.com/jckantor/TCLab/archive/master.zip
```

until a new package can be deployed for pip install. We appreciate you understanding as we take some time to make the transition in a way that builds upon Jeff's legacy with new innovations. We are currently developing a new `pyscript` module that can run the TCLab exercises directly from a web-browser or directly from a Jupyter notebook without the need to pip install the package.

**Comment by kjkoster** [comment]
Oh, I was not aware. That is sad news.

**Comment by APMonitor** [comment]
TCLab v1.0.0 is now released and resolves this isssue. The most current package is updated at https://github.com/APMonitor/TCLab  To upgrade, use:

```bash
pip install tclab --upgrade
```
