### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#15]
The package `setup.py` claims Python 2 compatibility, but I think currently things will break. I know at least of the following problems:

* We use the print function 
* We assume / will yield a float
* We assume things about how string encoding is handled

**Comment by jckantor** [comment]
I added __future__ for both print and /.   Haven't tested string encoding, and also should look at the places where we are doing exception handling.

**Comment by jckantor** [comment]
I coded any problematic strings as unicode for backward compatibility with Python 2.
