### ISSUE TITLE
Create a tag for the 0.1.1 release

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#29]
We should create tags when we push to PyPI (I've added the instructions on how to the development guide in 1fa82979a107472b791155aeca449817dcc341b5). But we should at least retroactively tag the commit which corresponds to the (currently active on PyPI) 0.1.1 release.

**Comment by alchemyst** [comment]
You need to push the tag for it to show up here, use `git push --tags`

**Comment by jckantor** [comment]
Is it ok now?

**Comment by alchemyst** [comment]
Yes. Here's where you check:

![branches](https://user-images.githubusercontent.com/236588/35048436-b65a93c6-fba5-11e7-9248-564023a5ee4a.png)
