### ISSUE TITLE
Develop test suite

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#30]
With a device plugged in, we should be able to run a completely automated test which excercises all of the API without user interaction.

**Comment by jckantor** [comment]
Yes, we need a test suite.  It would be a separate issue, but we should also be enable use of the module without a device plugged in for the development of scripts outside of a normal lab setting.

**Comment by alchemyst** [comment]
I think we have a good enough test suite for me to close this now. I'll add specific shortcomings as other issues.
