### ISSUE TITLE
End of line in sketch

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#32]
The sketch defines `const char nl = '\n'` but doesn't use it, and later has a hard-coded '\n' in the `readCommand` routine.

**Comment by jckantor** [comment]
Replaced \n with nl in the readCommand function.  The \r was added by Vocareum, and I'm not sure if that's related to their implementation of a channel function on their server. Need to clarify with them their end-of-line assumptions.

**Comment by alchemyst** [comment]
The [Arduino docs](https://www.arduino.cc/en/Serial/Println) say "println() Prints data to the serial port as human-readable ASCII text followed by a carriage return character (ASCII 13, or '\r') and a newline character (ASCII 10, or '\n')."

So the lab will do \r\n out, and I guess the extra "\r" is so that it accepts Windows conventions when coming in.
