### ISSUE TITLE
Create long-running frontend for manual interaction with lab

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#43]
I'm thinking of something with buttons which you can press to make things happen and just "current" output values instead of graphs.

**Comment by jckantor** [comment]
How about a Display class which creates an object that can display whatever the historian is tracking.  So 

h = Historian(a.sources)
d = Display(h)

Then d.update() would provide a display of current variables.  The display might have options, such as a plain text that overwrites itself, or perhaps something more graphical that looks like a real instrument.

**Comment by jckantor** [comment]
The options would go like so ...

h  = Historian(a.sources)
d = Display(h, options)

**Comment by jckantor** [comment]
Thinking about this some more, suppose we introduce a class called Reporter.  The subclasses of reporter would include Plotter and other objects which provide real-time diagnostics. Reporters would have an update() method that would update the historian and display.  Ideally one could instrument an experiment with one more historians and associated Reporters.

Does that make sense?

**Comment by alchemyst** [comment]
I have created the interface I had in mind via the Jupyter notebook. This version doesn't do any logging or plotting (yet) but provides a front-end for the lab which students can use to interact. It has the benefit of having no growing components, so there is in principle no limit to how long it can run.
