### ISSUE TITLE
Generate statically hosted documentation

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#57]
We can use the current notebooks to generate documentation for the module and host it on readthedocs. [This tool](http://sphinx-ipynb.readthedocs.io/en/latest/howto.html) appears to allow for this.

**Comment by jckantor** [comment]
Check out ... http://tclab.readthedocs.io/en/latest/index.html   This is generated using nbsphinx.  The one thing I haven't figured out is how to to have the notebooks executed in place prior to loading to readthedocs. Until then we'll need to leave notebooks with outputs as they are to appear in the docs.
