### ISSUE TITLE
Consistent support for time throughout the package

### ISSUE THREAD

**Issue by jckantor** [jckantor/TCLab#74]
We need a method to determine time that can be used by all modules in the package, and which can be configured in setup.

One way might be to have TCLab.time() and TCLabModel.time() that can be initialized through the class __init__ with a factor speedup. Conceptually this would be the experiment telling us what time it is.  The default would be an initial time of zero and speedup=1.

**Comment by alchemyst** [comment]
I think we can close this one, right?
