### ISSUE TITLE
The initial connection code is actually broken

### ISSUE THREAD

**Issue by jckantor** [jckantor/TCLab#91]
The urgent need to get the connection code working has introduced some bugs.  This code should be factored into a testable `findport` function.

**Comment by alchemyst** [comment]
I actually did this refactor this morning and called it `find_arduino`. See commits 4bd34e48593c5e81996ab19401de31930e35ab53 and 7de583065d9afcfbcc078bc5f92c81e49d1588b4

At the moment it just does the same thing as it used to, but at least it is a separate function.

**Comment by alchemyst** [comment]
@jckantor can we close this?
