### ISSUE TITLE
Add a flag for clock which is guaranteed not to error

### ISSUE THREAD

**Issue by alchemyst** [jckantor/TCLab#99]
One of the most frequent complaints I'm getting from students is that `clock` loses sync and then raises an error during long runs. For instance, they may want to schedule several long runs overnight, but clock loses sync 20 minutes into the run. This can be very frustrating, especially if the overrun is not very large.

I suggest a flag which allows for overruns and returns the difference in time steps between this and the next time step so that users can handle this correctly in their code, something like:

```python
for dt, t in clock(1000, overrun=True):
    # use dt to for instance do integration calculations correctly.
```

**Comment by jckantor** [comment]
So I've set the default tol to float('inf') which never error.  The returned t is now set to 2 digits, so users can compute dt to the 100th second.
